### ISSUE TITLE
jenkins 사용하지 않는 경우 배포 처리

### ISSUE THREAD

**Issue by dyKim50137** [jht3820/luna-pipe#1482]
### 기존 기능의 문제점

현재는 Jenkins Job을 토한 배포가능
- Jenkins 를 사용하지 않고, shell script를 이용해서 배포하는 경우에 대해 처리 할 수 없음

### 새로운 기능 제안
Jenkins 사용하지 않고 쉘 파일 실행으로 하는 경우에 대해서
어떤 식으로 배포할 지 설정하는 기능과
쉘 파일실행으로 배포하는 경우 쉘  실행 기능도 추가되었으면 합니다.

**Comment by jht3820** [comment]
현재는 서버에 있는 쉘 파일 위치 정보만 별도의 properties에 작성해두고
쉘을 실행할 수 있도록 기능 추가하였습니다.

쉘을 수정 하는것, 쉘파일 위치 같은 정보가 기록된 properties 파일을 화면에서 수정하는 것 등의 기능은
추후 추가할 예정입니다.
