### ISSUE TITLE
Jenkins 에서 폴더 생성 후 해당 폴더안에 JOB 생성 시 문제

### ISSUE THREAD

**Issue by wisteria4301** [jht3820/luna-pipe#867]
### Steps 
Jenkins 에서 폴더 생성 후 해당 폴더안에 JOB 생성 시 문제

### Description :

1. Jenkins 에서 디렉토리 생성
2. 디렉토리 생성 후 해당 디렉토리에 JOB 생성
3. LUNA PIPE에서 JOB 등록 팝업에서 (2)에서 생성한 JOB이 정상 표출되지 않음

디렉토리 구조로 JOB이 생성되었을때  처리 필요합니다.

**Comment by jht3820** [comment]
jenkins에서 JOB 이 디렉토리로 있을때 처리를 추가하였습니다.
