### ISSUE TITLE
Job 빌드 실행 팝업의 속도 문제

### ISSUE THREAD

**Issue by hohyunchoi** [jht3820/luna-pipe#887]
### Steps 

JOB 빌드 로그가 많은 경우 브라우저 속도가 느린 문제 있습니다.

### Description :

여러 연관된 소스를 컴파일 하고, 각종 처리를하는  JOB에서는 빌드 로그가 많이 쌓입니다.
JOB 실행 화면에서 실제 Jenkins JOB 빌드 로그를 실시간으로 가져와서 보여주다 보니
빌드 로그가 많을 시 브라우저 속도가 굉장히 느려지는 문제 있습니다.

빌드 로그를 보여주는 방법이 변경되어야 될것같습니다.

**Comment by jht3820** [comment]
해당 부분은 Jenkins 화면 링크로 대체하였습니다.
