### ISSUE TITLE
JOB 기본 파라미터 세팅되어 있을 경우 PIPE에서 자동 세팅

### ISSUE THREAD

**Issue by dyKim50137** [jht3820/luna-pipe#888]
### 기존 기능의 문제점
JOB 파라미터 정보를 수동으로 입력하는 것이 편의성이 떨어집니다.

### 새로운 기능 제안
Jenkin 에 등록된 JOB 목록을 가져와서 PIPE에 등록할 때 Job에 빌드 파라미터가 있다면
자동으로 가져와서 PIPE에도 정보 세팅하도록 하는 기능이 필요할것 같습니다.

**Comment by jht3820** [comment]
현재 PIPE에서 파라미터 자동 세팅하도록 수정되었습니다.
